defaultHearts: 30
maxHearts: 40

anarchiczneSerce:
  material: GUNPOWDER
  meta:
    display-name: "<red>Anarchiczne Serce</red>"
    lore:
      - "<gray>Użyj, aby zwiększyć liczbę serc o </gray><red>+1</red><gray>.</gray>"
      - "<gray>Limit: </gray><red>{maxHearts}</red><gray>.</gray>"
    enchantments:
      minecraft:density: 1
    flags:
      - HIDE_ENCHANTS
      - HIDE_ATTRIBUTES
anarchiczneSerceCustomModelData: 0

blockedEndCrystalEnvironments:
  - NETHER
blockedEndCrystalWorlds:
  - spawn

trash:
  title: "Kosz"
  rows: 5
  clearMessage: "{prefix}<red>Usunięto itemy z kosza.</red>"

combatlog:
  tagDurationSeconds: 15
  killOnLogout: true

messages:
  prefix: "<dark_gray>[</dark_gray><red>Anarchia</red><dark_gray>] </dark_gray><gray>"
  noPermission: "{prefix}<red>Brak uprawnień.</red>"
  reloadDone: "{prefix}<green>Przeładowano config.</green>"
  giveUsage: "{prefix}<red>Użycie: /anarchiacore heart give <player> [amount]</red>"
  setItemUsage: "{prefix}<red>Użycie: /anarchiacore heart setitem (trzymaj item w ręce)</red>"
  setItemDone: "{prefix}<green>Zapisano definicję anarchicznego serca z trzymanego przedmiotu.</green>"
  notAPlayer: "{prefix}<red>Ta komenda jest tylko dla gracza.</red>"
  heartUsed: "{prefix}<green>Zwiększono serca do: </green><yellow>{hearts}</yellow><red>❤</red>"
  heartMax: "{prefix}<red>Masz już maksymalną liczbę serc: </red><yellow>{maxHearts}</yellow><red>❤</red>"
  heartLostOnDeath: "{prefix}<red>Straciłeś 1 serce za śmierć. Masz teraz: </red><yellow>{hearts}</yellow><red>❤</red>"
  crystalBlocked: "{prefix}<red>Nie można stawiać kryształów Endu w tym wymiarze.</red>"
  trashOpened: "{prefix}<gray>Otworzono kosz. Itemy zostaną usunięte po zamknięciu.</gray>"
  trashCleared: "{prefix}<red>Usunięto itemy z kosza.</red>"
  combatlog:
    tagged: "{prefix}<red>Jesteś w combatlogu.</red>"
    logoutPunish: "{prefix}<red>Wylogowałeś się podczas walki.</red>"
    spawned: "{prefix}<green>Totem ułaskawił Cię, przeniesiono na spawn.</green>"
  customItems:
    giveUsage: "{prefix}<red>Użycie: /anarchiacore customitems give <item> [player]</red>"
    invalidPlayer: "{prefix}<red>Nie znaleziono gracza.</red>"
    notFound: "{prefix}<red>Nie znaleziono itemu: </red><yellow>{item}</yellow>"
    give: "{prefix}<green>Dano item </green><yellow>{item}</yellow><green> graczowi </green><yellow>{player}</yellow><green>.</green>"
    list: "{prefix}<gray>Dostępne itemy: </gray><yellow>{items}</yellow>"
    explosivesBlocked: "{prefix}<red>W tym regionie nie można używać Bombardy Maxima ani dynamitu.</red>"
    regionBlocked: "{prefix}<red>Nie możesz użyć tego itemu w tym regionie.</red>"
    noSpace: "{prefix}<red>Brak miejsca na postawienie Turbo Trapa.</red>"
